openapi: 3.0.0
info:
  contact:
    email: ronald.jc@hotmail.com
  description: consuming mail api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Mail api
  version: 1.0.0
servers:
- url: https://localhost:8080/busca/v1
- url: http://localhost:8080/busca/v1
paths:
  /busca/{cep}:
    get:
      description: return an address
      operationId: getAddress
      parameters:
      - explode: false
        in: path
        name: cep
        required: true
        schema:
          pattern: '[0-9]{5}-[0-9]{3}'
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
          description: successful operation
        "400":
          content:
            application/json:
              examples:
                response:
                  value:
                    message: Id Formated Invalid
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid Id
        "404":
          content:
            application/json:
              examples:
                response:
                  value:
                    message: Not found
              schema:
                $ref: '#/components/schemas/Error'
          description: Employee not found
        "500":
          content:
            application/json:
              examples:
                response:
                  value:
                    message: Internal Server Error
              schema:
                $ref: '#/components/schemas/Error'
          description: Server Error
      summary: return an address
      tags:
      - consult
      x-accepts: application/json
      x-tags:
      - tag: consult
components:
  schemas:
    Address:
      example:
        bairro: Belo comeco
        cep: "12345678"
        cidade: Belo fim
        complemento: Casa
        endereco: Rua dos Abc
        uf: Mg
      properties:
        bairro:
          type: string
        cep:
          type: string
        cidade:
          type: string
        complemento2:
          type: string
        end:
          type: string
        uf:
          type: string
      type: object
    Error:
      properties:
        message:
          type: string
